---
title: "Accelerometer Data Prediction"
author: "Vindhya Mullapudi"
date: "9/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Background
Participants were asked to life barbells and were then classified into groups A-E based on their abilities. There were accelerometers located on their belt, forearm, and arm.

# Method
1) Question  
2) Input  
3) Features  
4) Algorithm  
5) Prediction   
6) Evaluation  

# Setup
```{r, eval =FALSE}
library(caret)
set.seed(1603)

trainingFilename <- 'pml-training.csv'
testingFielname <- 'pml-testing.csv'
testingUrl <- 'https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv'
trainingUrl <- 'https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv'
```
# Filtering Data
```{r, eval =FALSE}
training.df <-read.csv(trainingFilename, na.strings=c("NA","","#DIV/0!"))
training.df <-training.df[,colSums(is.na(training.df))==0]
dim(training.df)

testing.df <- read.csv(testingFielname , na.strings=c("NA","","#DIV/0!"))
testing.df <- testing.df[,colSums(is.na(testing.df))==0]
dim(testing.df)

training.df   <-training.df[,-c(1:7)]
testing.df <- testing.df[,-c(1:7)]
dim(training.df)

Training.nzv <- nearZeroVar(training.df[,-ncol(training.df)],saveMetrics=TRUE)
rownames(Training.nzv)
dim(Training.nzv)
```
# Algorithm 
```{r, eval =FALSE}
inTrain     <- createDataPartition(training.df$classe, p = 0.6, list = FALSE)
inTraining  <- training.df[inTrain,]
inTest      <- training.df[-inTrain,]
dim(inTraining);dim(inTest)

myModelFilename <- "myModel.RData"
if (!file.exists(myModelFilename)) {

    # Parallel cores  
    #require(parallel)
    library(doParallel)
    ncores <- makeCluster(detectCores() - 1)
    registerDoParallel(cores=ncores)
    getDoParWorkers() # 3    
    
    # use Random Forest method with Cross Validation, 4 folds
    myModel <- train(classe ~ .
                , data = inTraining
                , method = "rf"
                , metric = "Accuracy"  # categorical outcome variable so choose accuracy
                , preProcess=c("center", "scale") # attempt to improve accuracy by normalising
                , trControl=trainControl(method = "cv"
                                        , number = 4 # folds of the training data
                                        , p= 0.60
                                        , allowParallel = TRUE 
#                                       , seeds=NA # don't let workers set seed 
                                        )
                )

    save(myModel, file = "myModel.RData")
    # 3:42 .. 3:49 without preProcess
    # 3:51 .. 3:58 with preProcess
    stopCluster(ncores)
} else {
    # Use cached model  
    load(file = myModelFilename, verbose = TRUE)
}
print(myModel, digits=4)
```
# Prediction
```{r, eval =FALSE}
predTest <- predict(myModel, newdata=inTest)
```
# Evaluation
```{r, eval =FALSE}
confusionMatrix(predTest, inTest$classe)
myModel$finalModel
varImp(myModel)
print(predict(myModel, newdata=testing.df))
```